#!/usr/bin/zsh

alias ga="git add ."
alias gc="git commit"
alias gca="git commit --amend"
alias gch="git checkout"
alias gd1="git diff HEAD"
alias gd="git diff"
alias gp="git pull --rebase"
alias grc="git rebase --continue"
alias gri="git rebase --interactive"
alias gs="git status"
alias ipy="~/tools/venvs/main/bin/ipython"
alias la="ls -fHalo --color=auto"
alias ls="ls --color=auto"
alias py="$HOME/tools/venvs/main/bin/python3"
alias venv="source $HOME/tools/venvs/main/bin/activate"
alias wdiff="git diff --color-words --no-index"

function cargo_list() {
    cargo install --list | rg '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' '
}
